source 'https://rubygems.org'

gem 'sprockets', '~> 3.7.2'
gem 'sprockets-export'
gem 'sprockets-svgo'
gem 'coffee-script'
gem 'coffee-script-source', '~> 1.9.1'
gem 'eco'
gem 'sass'
gem 'uglifier'
gem 'blade'
gem 'github_api'
gem 'puma'
